SEED_RECIPES = [
    {
        "name": 'Soup of the Day',
        "category": 'Soup',
        "gluten_free": False,
        "notes": 'Selection changes daily',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Pull Apart Garlic Bread',
        "category": 'Appetizer',
        "gluten_free": False,
        "notes": '',
        "instructions": '',
        "ingredients": [
            {"name": 'Baguette', "quantity": '1', "unit": '', "sort_order": 0},
            {"name": 'Butter', "quantity": '4', "unit": 'tbsp', "preparation": 'melted', "sort_order": 1},
            {"name": 'Garlic', "quantity": '3', "unit": 'cloves', "preparation": 'minced', "sort_order": 2},
        ],
    },
    {
        "name": 'Tuna Tataki',
        "category": 'Appetizer',
        "gluten_free": True,
        "notes": 'Gluten-free option',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'TBM Lump Crabcakes',
        "category": 'Appetizer',
        "gluten_free": False,
        "notes": 'Seasonal interpretation',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Fried Chicken Livers',
        "category": 'Appetizer',
        "gluten_free": False,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Smoked Trout Croquettes',
        "category": 'Appetizer',
        "gluten_free": False,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Sweet Potato Medallions',
        "category": 'Appetizer',
        "gluten_free": True,
        "notes": 'Gluten-free option',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Portabella Stuffed Mushrooms',
        "category": 'Appetizer',
        "gluten_free": False,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Flash Fried Brussel Sprouts',
        "category": 'Appetizer',
        "gluten_free": False,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Artisanal Cheese Board',
        "category": 'Appetizer',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'After(t) Cheese Board',
        "category": 'Appetizer',
        "gluten_free": True,
        "notes": '(2 meats, 3 cheeses) with seasonal accompaniment',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Bucket of Pommes Frites',
        "category": 'Appetizer',
        "gluten_free": False,
        "notes": 'Served with dipping sauces',
        "instructions": '',
        "ingredients": [
            {"name": 'Potatoes', "quantity": '4', "unit": '', "preparation": 'cut into fries', "sort_order": 0},
            {"name": 'Salt', "quantity": '', "unit": '', "preparation": 'to taste', "sort_order": 1},
        ],
    },
    {
        "name": 'Caesar Salad',
        "category": 'Salad',
        "gluten_free": True,
        "notes": 'Gluten-free option',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Iceberg Wedge',
        "category": 'Salad',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Quinoa Salad',
        "category": 'Salad',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'House Greens',
        "category": 'Salad',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Steak Diane',
        "category": 'Main',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Bulgogi Braised Short Ribs',
        "category": 'Main',
        "gluten_free": False,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Pan-Seared Salmon',
        "category": 'Main',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Braised Volcano Cut Pork',
        "category": 'Main',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Balsamic Marinated Airline Chicken Breast',
        "category": 'Main',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Lowcountry Shrimp and Grits',
        "category": 'Main',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'TBM Cheeseburger',
        "category": 'Main',
        "gluten_free": False,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Garlic and Rosemary Roasted Fingerlings',
        "category": 'Side',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Fried Brussels with Feta and Bacon',
        "category": 'Side',
        "gluten_free": False,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Jalapeno Cheddar Grits',
        "category": 'Side',
        "gluten_free": True,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Daily Vegetable',
        "category": 'Side',
        "gluten_free": True,
        "notes": 'ask server',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Pommes Frites',
        "category": 'Side',
        "gluten_free": False,
        "notes": '',
        "instructions": '',
        "ingredients": [],
    },
    {
        "name": 'Homemade Natural Gatorade Electrolyte Drink',
        "category": 'Beverage',
        "gluten_free": True,
        "notes": 'Source: Piedmont Eastside Dietitians. Use fresh, high-quality ingredients for the best flavor. Store leftovers in a sealed container in the refrigerator for up to 2 days.',
        "instructions": '1. In a large pitcher, combine the water or coconut water with freshly squeezed orange juice and freshly squeezed lemon juice.\n2. Stir in sea salt until dissolved. Sea salt helps replenish electrolytes lost through sweat.\n3. If desired, add honey, agave nectar, or maple syrup to sweeten the drink to your liking. Stir until the sweetener is fully dissolved.\n4. Chill in the refrigerator for at least 30 minutes to allow the flavors to meld together and for the drink to become cold.\n5. If desired, garnish with slices of orange and/or lemon for a decorative touch.',
        "ingredients": [
            {"name": 'Water or coconut water', "quantity": '2', "unit": 'cups', "sort_order": 0},
            {"name": 'Juice (orange, grape, or cranberry)', "quantity": '1/2', "unit": 'cup', "preparation": 'use 100% fresh/natural', "sort_order": 1},
            {"name": 'Lemon juice', "quantity": '1/4', "unit": 'cup', "preparation": 'freshly squeezed', "sort_order": 2},
            {"name": 'Sea salt', "quantity": '1/4', "unit": 'tsp', "sort_order": 3},
            {"name": 'Honey, agave nectar, or maple syrup', "quantity": '2', "unit": 'tbsp', "preparation": 'for sweetness', "optional": True, "sort_order": 4},
            {"name": 'Oranges and lemons', "quantity": '', "unit": '', "preparation": 'sliced, for garnish', "optional": True, "sort_order": 5},
        ],
    },
    {
        "name": 'Air-Fried Peruvian Chicken Drumsticks with Green Crema',
        "category": 'Main',
        "gluten_free": True,
        "notes": 'Source: Allrecipes. Any extra sauce can be stored in an airtight container and refrigerated for up to 5 days. Use as a salad dressing, baked potato topper, or on tacos.',
        "instructions": '1. Brush an air fryer basket with olive oil.\n2. Combine honey, 1 tablespoon olive oil, garlic, salt, cumin, paprika, oregano, and pepper in a large bowl. Add drumsticks; toss to coat. Arrange drumsticks vertically in the prepared basket, leaning against the basket wall and one another.\n3. Cook in the air fryer at 400 degrees F (200 degrees C) until an instant-read thermometer inserted in the thickest part of drumstick reads 165 degrees F (74 degrees C), 15 to 20 minutes. Rearrange drumsticks with kitchen tongs halfway through cooking for even cooking.\n4. Meanwhile, make sauce: Combine spinach, sour cream, cilantro, jalapeno, lime juice, garlic, salt, and pepper in the bowl of a food processor; process until crema sauce is smooth.\n5. Drizzle some crema sauce over drumsticks and serve with remaining crema.',
        "prep_time": '15 mins',
        "cook_time": '15 mins',
        "total_time": '30 mins',
        "servings": '6',
        "ingredients": [
            {"name": 'Olive oil', "quantity": '', "unit": '', "preparation": 'for brushing', "sort_order": 0},
            {"name": 'Honey', "quantity": '1', "unit": 'tbsp', "sort_order": 1},
            {"name": 'Olive oil', "quantity": '1', "unit": 'tbsp', "sort_order": 2},
            {"name": 'Garlic', "quantity": '2', "unit": 'cloves', "preparation": 'grated', "sort_order": 3},
            {"name": 'Salt', "quantity": '1', "unit": 'tsp', "sort_order": 4},
            {"name": 'Ground cumin', "quantity": '1', "unit": 'tsp', "sort_order": 5},
            {"name": 'Smoked paprika', "quantity": '1/2', "unit": 'tsp', "sort_order": 6},
            {"name": 'Dried oregano', "quantity": '1/2', "unit": 'tsp', "sort_order": 7},
            {"name": 'Ground black pepper', "quantity": '1/4', "unit": 'tsp', "sort_order": 8},
            {"name": 'Chicken drumsticks', "quantity": '6', "unit": '', "preparation": '4 ounce each', "sort_order": 9},
            {"name": 'Baby spinach leaves', "quantity": '1', "unit": 'cup', "preparation": 'stems removed', "sort_order": 10},
            {"name": 'Sour cream', "quantity": '3/4', "unit": 'cup', "sort_order": 11},
            {"name": 'Cilantro leaves', "quantity": '1/4', "unit": 'cup', "sort_order": 12},
            {"name": 'Jalapeno pepper', "quantity": '1/2', "unit": '', "preparation": 'seeded', "sort_order": 13},
            {"name": 'Fresh lime juice', "quantity": '2', "unit": 'tbsp', "sort_order": 14},
            {"name": 'Garlic', "quantity": '1', "unit": 'clove', "preparation": 'smashed', "sort_order": 15},
            {"name": 'Salt', "quantity": '1/4', "unit": 'tsp', "preparation": 'for crema', "sort_order": 16},
            {"name": 'Ground black pepper', "quantity": '1/4', "unit": 'tsp', "preparation": 'for crema', "sort_order": 17},
        ],
    },
    {
        "name": 'Triple Berry Crisp',
        "category": 'Dessert',
        "gluten_free": False,
        "notes": 'Source: Allrecipes. Delicious served warm with whipped cream.',
        "instructions": '1. Gather all ingredients.\n2. Preheat the oven to 350 degrees F (175 degrees C).\n3. Gently toss together blackberries, raspberries, blueberries, and white sugar in a large bowl; set aside.\n4. Combine flour, oats, brown sugar, cinnamon, and nutmeg in a separate large bowl. Cut in butter with 2 knives or a pastry blender until crumble mixture resembles coarse crumbs.\n5. Press 1/2 of the crumble into the bottom of a 9x13-inch pan.\n6. Cover with berry mixture. Sprinkle remaining crumble over berries.\n7. Bake in the preheated oven until fruit is bubbly and the top is golden brown, 30 to 40 minutes.\n8. Serve with whipped cream. Enjoy!',
        "prep_time": '20 mins',
        "cook_time": '30 mins',
        "total_time": '50 mins',
        "servings": '18',
        "ingredients": [
            {"name": 'Fresh blackberries', "quantity": '1 1/2', "unit": 'cups', "sort_order": 0},
            {"name": 'Fresh raspberries', "quantity": '1 1/2', "unit": 'cups', "sort_order": 1},
            {"name": 'Fresh blueberries', "quantity": '1 1/2', "unit": 'cups', "sort_order": 2},
            {"name": 'White sugar', "quantity": '1/4', "unit": 'cup', "sort_order": 3},
            {"name": 'All-purpose flour', "quantity": '2', "unit": 'cups', "sort_order": 4},
            {"name": 'Rolled oats', "quantity": '2', "unit": 'cups', "sort_order": 5},
            {"name": 'Packed brown sugar', "quantity": '1 1/2', "unit": 'cups', "sort_order": 6},
            {"name": 'Ground cinnamon', "quantity": '1', "unit": 'tsp', "sort_order": 7},
            {"name": 'Ground nutmeg', "quantity": '1/2', "unit": 'tsp', "sort_order": 8},
            {"name": 'Cold butter', "quantity": '1 1/2', "unit": 'cups', "preparation": 'cubed', "sort_order": 9},
        ],
    },
    {
        "name": 'Basic Beef Stew (Instant Pot)',
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: Recipes.InstantPot.com. Instead of 2 lb of stew meat, you can purchase a 2 1/2 to 3 lb beef chuck roast and cut it yourself. Trim off the fat and cut into 2-inch pieces. Top with chopped fresh parsley for a pretty, fresh garnish.',
        "instructions": '1. In large bowl, toss beef with salt and pepper. Spray 6-quart Instant Pot insert with cooking spray. Select SAUTE; adjust to normal. Melt butter in insert. Add beef in 2 batches, and cook 2 to 4 minutes on first side until browned. Turn and cook 2 to 4 minutes longer on second side or until browned. Select CANCEL.\n2. Return beef to insert. Stir in tomato paste. Stir in onions, carrots and potatoes. Stir in broth. Secure lid; set pressure valve to SEALING. Select MANUAL; cook on high pressure 45 minutes. Select CANCEL. Set pressure valve to VENTING to quick-release pressure.\n3. In small bowl, beat cornstarch and water with whisk. Select SAUTE, and adjust to normal; heat liquid to simmering. Gently stir in cornstarch mixture; cook 30 to 60 seconds, stirring frequently, until thickened. Select CANCEL.',
        "prep_time": '45 mins',
        "cook_time": '54 mins',
        "servings": '8',
        "ingredients": [
            {"name": 'Beef stew meat', "quantity": '2', "unit": 'lb', "sort_order": 0},
            {"name": 'Salt', "quantity": '2', "unit": 'tsp', "sort_order": 1},
            {"name": 'Pepper', "quantity": '1', "unit": 'tsp', "sort_order": 2},
            {"name": 'Butter', "quantity": '2', "unit": 'tbsp', "sort_order": 3},
            {"name": 'Tomato paste', "quantity": '1', "unit": 'tbsp', "preparation": 'organic', "sort_order": 4},
            {"name": 'Onions', "quantity": '2', "unit": 'cups', "preparation": 'chopped', "sort_order": 5},
            {"name": 'Carrots', "quantity": '2', "unit": 'cups', "preparation": 'diced, peeled, 1-inch', "sort_order": 6},
            {"name": 'Russet potatoes', "quantity": '2', "unit": 'cups', "preparation": 'diced, peeled, 1-inch', "sort_order": 7},
            {"name": 'Beef flavored broth', "quantity": '1', "unit": 'cup', "sort_order": 8},
            {"name": 'Cornstarch', "quantity": '2', "unit": 'tbsp', "sort_order": 9},
            {"name": 'Water', "quantity": '2', "unit": 'tbsp', "sort_order": 10},
        ],
    },
    {
        "name": 'Scalloped Taters',
        "category": 'Side',
        "gluten_free": False,
        "notes": 'Source: Just A Pinch, by Brooke Dudgeon',
        "instructions": '1. Melt butter in saucepan. Add flour and milk, whisk. Add cheese. Cook until it thickens up and cheese has melted.\n2. In 9x13 pour a little cheese sauce, sliced potatoes, diced onion. Repeat once but leave enough cheese sauce to top with.\n3. Bake uncovered at 350 for 1 hour. Stick under broiler to brown up after the 1 hour.',
        "cook_time": '1 hr',
        "servings": '6-8',
        "ingredients": [
            {"name": 'Medium potatoes', "quantity": '5-6', "unit": '', "preparation": 'sliced', "sort_order": 0},
            {"name": 'Onion', "quantity": '1', "unit": '', "preparation": 'diced', "sort_order": 1},
            {"name": 'Butter', "quantity": '2', "unit": 'tbsp', "sort_order": 2},
            {"name": 'Flour', "quantity": '1/2', "unit": 'cup', "sort_order": 3},
            {"name": 'Milk', "quantity": '2', "unit": 'cups', "sort_order": 4},
            {"name": 'Cheddar cheese', "quantity": '2', "unit": 'cups', "sort_order": 5},
        ],
    },
    {
        "name": 'Creamy Au Gratin Potatoes',
        "category": 'Side',
        "gluten_free": False,
        "notes": 'Source: Food.com, by Lavender Lynn. Great side dish with a roast pork loin or beef tenderloin.',
        "instructions": '1. Preheat oven to 400 degrees F (200 degrees C).\n2. Butter a 1 quart casserole dish.\n3. Layer 1/2 of the potatoes into bottom of the prepared casserole dish.\n4. Top with the onion slices, and add the remaining potatoes.\n5. Season with salt and pepper to taste.\n6. In a medium-size saucepan, melt butter over medium heat.\n7. Mix in the flour and salt, and stir constantly with a whisk for one minute. Stir in milk. Cook until mixture has thickened.\n8. Stir in cheese all at once, and continue stirring until melted, about 30 to 60 seconds.\n9. Pour cheese over the potatoes, and cover the dish with aluminum foil.\n10. Bake 1 1/2 hours in the preheated oven.',
        "total_time": '2 hrs',
        "servings": '4',
        "ingredients": [
            {"name": 'Russet potatoes', "quantity": '4', "unit": '', "preparation": 'sliced into 1/4 inch slices', "sort_order": 0},
            {"name": 'Onion', "quantity": '1', "unit": '', "preparation": 'sliced into rings', "sort_order": 1},
            {"name": 'Salt and pepper', "quantity": '', "unit": '', "preparation": 'to taste', "sort_order": 2},
            {"name": 'Butter', "quantity": '3', "unit": 'tbsp', "sort_order": 3},
            {"name": 'All-purpose flour', "quantity": '3', "unit": 'tbsp', "sort_order": 4},
            {"name": 'Salt', "quantity": '1/2', "unit": 'tsp', "sort_order": 5},
            {"name": 'Milk', "quantity": '2', "unit": 'cups', "sort_order": 6},
            {"name": 'Cheddar cheese', "quantity": '1 1/2', "unit": 'cups', "preparation": 'shredded', "sort_order": 7},
        ],
    },
    {
        "name": 'Southern Style Collard Greens',
        "category": 'Side',
        "gluten_free": True,
        "notes": 'Source: Allrecipes, by tybright31. Turkey necks can be substituted for the ham hocks. Cook for 45 minutes instead of 2 hours.',
        "instructions": '1. Combine onions, ham hocks, and garlic in a stockpot; add chicken broth. Cook mixture over medium heat until meat is falling off the bone, about 2 hours.\n2. Stir collard greens, vinegar, sugar, salt, and pepper into the broth mixture; cook until greens have reached desired tenderness, about 2 more hours.',
        "prep_time": '15 mins',
        "cook_time": '4 hrs',
        "total_time": '4 hrs 15 mins',
        "servings": '10',
        "ingredients": [
            {"name": 'Sweet onions', "quantity": '2', "unit": '', "preparation": 'finely chopped', "sort_order": 0},
            {"name": 'Smoked ham hocks', "quantity": '2', "unit": '', "sort_order": 1},
            {"name": 'Garlic', "quantity": '4', "unit": 'cloves', "preparation": 'finely chopped', "sort_order": 2},
            {"name": 'Chicken broth', "quantity": '3', "unit": '32 oz containers', "sort_order": 3},
            {"name": 'Collard greens', "quantity": '3', "unit": '1 lb packages', "preparation": 'trimmed', "sort_order": 4},
            {"name": 'Apple cider vinegar', "quantity": '1/3', "unit": 'cup', "sort_order": 5},
            {"name": 'White sugar', "quantity": '2', "unit": 'tbsp', "sort_order": 6},
            {"name": 'Salt', "quantity": '1 1/2', "unit": 'tsp', "preparation": 'or to taste', "sort_order": 7},
            {"name": 'Ground black pepper', "quantity": '3/4', "unit": 'tsp', "preparation": 'or to taste', "sort_order": 8},
        ],
    },
    {
        "name": 'Popcorn Chicken with Creamy Avocado Sauce and Green Beans',
        "category": 'Main',
        "gluten_free": False,
        "notes": '',
        "instructions": '1. Prep: Preheat oven to 450 degrees F with a rack in the upper third. Pat chicken dry, season with salt and pepper; trim green beans. Heat 3 tablespoons oil in a skillet over medium-high. Add panko with a pinch of salt and pepper. Cook until golden-brown (2-3 minutes). Transfer to a dish.\n2. Bread and Bake: Oil a rimmed baking sheet. Beat egg, 2 tablespoons water, salt, and pepper in a bowl. Dip chicken in egg, then dredge in panko. Place on one side of the baking sheet and drizzle with oil. Place green beans on the other side and toss with 2 tablespoons oil. Bake on the upper oven rack until chicken is golden-brown and green beans are tender (15-20 minutes).\n3. Creamy Avocado Sauce: Chop garlic. In a bowl, combine sour cream, guacamole, garlic, 1 teaspoon vinegar, and 2 tablespoons water. Season with salt and pepper.',
        "ingredients": [
            {"name": 'Guacamole', "quantity": '2', "unit": '2 oz packets', "sort_order": 0},
            {"name": 'Sour cream', "quantity": '3', "unit": 'packets', "sort_order": 1},
            {"name": 'Garlic clove', "quantity": '1', "unit": 'large', "sort_order": 2},
            {"name": 'Green beans', "quantity": '4', "unit": 'oz', "sort_order": 3},
            {"name": 'Boneless skinless chicken breasts', "quantity": '2', "unit": '1 lb packages', "sort_order": 4},
            {"name": 'Egg', "quantity": '1', "unit": 'large', "sort_order": 5},
            {"name": 'Kosher salt and ground pepper', "quantity": '', "unit": '', "preparation": 'to taste', "sort_order": 6},
            {"name": 'Olive oil', "quantity": '', "unit": '', "sort_order": 7},
            {"name": 'White wine vinegar', "quantity": '', "unit": '', "preparation": 'or apple cider vinegar', "sort_order": 8},
        ],
    },
    {
        "name": 'White Sauce (Cheese Sauce)',
        "category": 'Sauce',
        "gluten_free": False,
        "notes": 'Source: BettyCrocker.com. Handwritten addition: + 1/2 cup cheese.',
        "instructions": '1. In 1 1/2-quart saucepan, melt butter over low heat. Stir in flour, salt and pepper. Cook over medium heat, stirring constantly, until mixture is smooth and bubbly; remove from heat.\n2. Gradually stir in milk. Heat to boiling, stirring constantly; boil and stir 1 minute.\n3. Stir in cheese until melted.',
        "prep_time": '5 mins',
        "total_time": '10 mins',
        "servings": '16',
        "ingredients": [
            {"name": 'Butter', "quantity": '2', "unit": 'tbsp', "sort_order": 0},
            {"name": 'All-purpose flour', "quantity": '2', "unit": 'tbsp', "sort_order": 1},
            {"name": 'Salt', "quantity": '1/4', "unit": 'tsp', "sort_order": 2},
            {"name": 'Pepper', "quantity": '1/8', "unit": 'tsp', "sort_order": 3},
            {"name": 'Milk', "quantity": '1', "unit": 'cup', "sort_order": 4},
            {"name": 'Cheese', "quantity": '1/2', "unit": 'cup', "preparation": 'handwritten addition', "sort_order": 5},
        ],
    },
    {
        "name": 'Creamy Hamburger Potato Casserole',
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: Allrecipes, by Theresa',
        "instructions": '1. Preheat oven to 350 degrees F (175 degrees C). Grease a 7x11-inch baking pan.\n2. Heat a large skillet over medium-high heat. Cook and stir beef in the hot skillet until browned and crumbly, 5 to 7 minutes; drain and discard grease.\n3. Mix 1 can cream of mushroom soup, mushrooms, 3/4 cup milk, seasoned salt, and black pepper in a bowl; fold in potatoes.\n4. Spread half the potato mixture into the prepared baking pan; top with Cheddar cheese. Spoon 1/2 the ground beef over cheese layer. Top ground beef layer with remaining potato mixture; layer with remaining ground beef.\n5. Mix remaining 1 can cream of mushroom soup with 1/4 cup milk; pour mixture over ground beef layer.\n6. Bake in the preheated oven until casserole is bubbling, about 1 hour 20 minutes. Sprinkle French-fried onions over casserole; return to oven for 5 more minutes.',
        "prep_time": '20 mins',
        "cook_time": '1 hr 30 mins',
        "total_time": '1 hr 50 mins',
        "servings": '6',
        "ingredients": [
            {"name": 'Lean ground beef', "quantity": '1', "unit": 'lb', "sort_order": 0},
            {"name": 'Condensed cream of mushroom soup', "quantity": '2', "unit": '10.75 oz cans', "preparation": 'divided', "sort_order": 1},
            {"name": 'Sliced mushrooms', "quantity": '4', "unit": '4 oz cans', "preparation": 'drained', "sort_order": 2},
            {"name": 'Milk', "quantity": '1', "unit": 'cup', "preparation": 'divided', "sort_order": 3},
            {"name": 'Seasoned salt', "quantity": '1/2', "unit": 'tsp', "sort_order": 4},
            {"name": 'Ground black pepper', "quantity": '', "unit": '', "preparation": 'to taste', "sort_order": 5},
            {"name": 'Potatoes', "quantity": '4', "unit": 'cups', "preparation": 'peeled and thinly sliced', "sort_order": 6},
            {"name": 'Shredded Cheddar cheese', "quantity": '1/2', "unit": 'cup', "sort_order": 7},
            {"name": 'French-fried onions', "quantity": '3/4', "unit": 'cup', "sort_order": 8},
        ],
    },
    {
        "name": 'Butterkase Macaroni and Cheese',
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: BettyCrocker.com',
        "instructions": '1. Cook and drain macaroni as directed on package.\n2. In 10-inch skillet, melt butter over medium heat. Using whisk, stir in flour, salt and onion. Cook 2 to 3 minutes, or until mixture smells nutty and is lightly golden, stirring constantly with whisk.\n3. Add milk. Continue to beat with whisk, scraping bottom of skillet until mixture heats to boiling. Mixture will thicken. Remove from heat; add cheese and cilantro. Stir with whisk until smooth. Stir in drained macaroni.\n4. Serve with additional cilantro if desired.',
        "prep_time": '15 mins',
        "total_time": '30 mins',
        "servings": '4',
        "ingredients": [
            {"name": 'Uncooked elbow macaroni', "quantity": '2', "unit": 'cups', "sort_order": 0},
            {"name": 'Butter', "quantity": '2', "unit": 'tbsp', "sort_order": 1},
            {"name": 'All-purpose flour', "quantity": '2', "unit": 'tbsp', "sort_order": 2},
            {"name": 'Salt', "quantity": '1', "unit": 'tsp', "sort_order": 3},
            {"name": 'Onion', "quantity": '1', "unit": 'tbsp', "preparation": 'grated or very finely chopped', "sort_order": 4},
            {"name": 'Milk', "quantity": '2', "unit": 'cups', "sort_order": 5},
            {"name": 'Shredded Butterkase cheese', "quantity": '2', "unit": 'cups', "preparation": '8 oz', "sort_order": 6},
            {"name": 'Fresh cilantro or Italian parsley', "quantity": '1/4', "unit": 'cup', "preparation": 'chopped', "sort_order": 7},
        ],
    },
    {
        "name": 'Quinoa and Green Bean Salad',
        "category": 'Salad',
        "gluten_free": True,
        "notes": 'Source: Martha Stewart',
        "instructions": '1. Heat 1 tablespoon oil in saucepan over medium-high heat. Add onion and garlic, 1/4 teaspoon salt, and a pinch of pepper. Cook, stirring, until translucent, about 3 minutes. Stir in quinoa and cook for 1 minute. Add water. Bring to a boil. Reduce to a simmer and cook, covered, until water is absorbed, about 16 minutes. Remove from heat. Let stand 10 minutes; fluff with fork. Cool completely, about 25 minutes.\n2. Bring a large pot of water to a boil. Add 1 tablespoon salt and beans, cooking until bright green, about 4 minutes. Drain and rinse in cold water.\n3. Combine quinoa, green beans, and parsley. Dress with 1/4 cup olive oil, vinegar, 1/2 teaspoon salt, and pepper.',
        "servings": '10',
        "ingredients": [
            {"name": 'Extra-virgin olive oil', "quantity": '1 tbsp + 1/4 cup', "unit": '', "preparation": '1 tbsp for cooking, 1/4 cup for dressing', "sort_order": 0},
            {"name": 'Small onion', "quantity": '1', "unit": '', "preparation": 'minced', "sort_order": 1},
            {"name": 'Garlic', "quantity": '2', "unit": 'cloves', "preparation": 'minced', "sort_order": 2},
            {"name": 'Kosher salt and freshly ground pepper', "quantity": '', "unit": '', "sort_order": 3},
            {"name": 'Quinoa', "quantity": '1', "unit": 'cup', "sort_order": 4},
            {"name": 'Water', "quantity": '1 3/4', "unit": 'cups', "sort_order": 5},
            {"name": 'Green beans', "quantity": '1', "unit": 'lb', "preparation": 'trimmed, cut crosswise into 1-inch pieces', "sort_order": 6},
            {"name": 'Flat-leaf parsley leaves', "quantity": '1', "unit": 'cup', "sort_order": 7},
            {"name": 'Red-wine vinegar', "quantity": '3', "unit": 'tbsp', "sort_order": 8},
        ],
    },
    {
        "name": 'Warm Potato-Veggie Salad',
        "category": 'Salad',
        "gluten_free": True,
        "notes": 'Source: Martha Stewart',
        "instructions": '1. Place potatoes in a large pot; cover with water by 1 inch, and add 1 tablespoon salt. Bring to a boil; reduce to a simmer, and cook until potatoes are tender, 15 to 20 minutes. With a wire skimmer or slotted spoon, transfer potatoes to a large bowl (reserve water in pot).\n2. To the simmering water, add green beans, and cook until crisp-tender, 2 to 3 minutes. Drain and add to potatoes, along with mayonnaise, vinegar, scallion, and carrot. Toss to combine, and lightly mash; season with salt and pepper, and serve warm.',
        "prep_time": '10 mins',
        "total_time": '30 mins',
        "servings": '4',
        "ingredients": [
            {"name": 'Baking potatoes', "quantity": '1 1/2', "unit": 'lbs', "preparation": 'peeled and cut into 1-inch pieces', "sort_order": 0},
            {"name": 'Coarse salt and ground pepper', "quantity": '', "unit": '', "sort_order": 1},
            {"name": 'Green beans', "quantity": '6', "unit": 'oz', "preparation": 'trimmed and cut into 1-inch pieces (about 1 1/4 cups)', "sort_order": 2},
            {"name": 'Light mayonnaise', "quantity": '1/3', "unit": 'cup', "sort_order": 3},
            {"name": 'White-wine vinegar', "quantity": '2-3', "unit": 'tsp', "sort_order": 4},
            {"name": 'Scallion', "quantity": '1', "unit": '', "preparation": 'thinly sliced', "sort_order": 5},
            {"name": 'Carrot', "quantity": '1', "unit": '', "preparation": 'coarsely grated', "sort_order": 6},
        ],
    },
    {
        "name": 'One-Pot Creamy Chicken Alfredo',
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: PureWow',
        "instructions": '1. In a large sauce pot, heat the vegetable oil over medium-high heat. Add the chicken and season with salt and pepper. Cook, stirring regularly, until the chicken is browned, 6 to 8 minutes.\n2. Add the broth, fettuccine, milk and garlic to the sauce pot. Bring the mixture to a boil, then cover and reduce the heat to medium. Cook, stirring frequently, until all the liquid has been absorbed and the pasta is fully cooked, 13 to 15 minutes.\n3. Turn off the heat and stir in the Parmesan and parsley until the cheese has melted; season with salt and pepper.',
        "servings": '6',
        "ingredients": [
            {"name": 'Vegetable oil', "quantity": '1', "unit": 'tbsp', "sort_order": 0},
            {"name": 'Boneless skinless chicken breasts', "quantity": '2', "unit": '', "preparation": 'cut into 3/4-inch pieces', "sort_order": 1},
            {"name": 'Kosher salt and freshly ground black pepper', "quantity": '', "unit": '', "sort_order": 2},
            {"name": 'Chicken broth', "quantity": '4', "unit": 'cups', "sort_order": 3},
            {"name": 'Fettuccine', "quantity": '1', "unit": 'lb', "sort_order": 4},
            {"name": 'Milk', "quantity": '1', "unit": 'cup', "sort_order": 5},
            {"name": 'Garlic cloves', "quantity": '2', "unit": '', "preparation": 'minced', "sort_order": 6},
            {"name": 'Freshly grated Parmesan cheese', "quantity": '1/2', "unit": 'cup', "sort_order": 7},
            {"name": 'Fresh parsley', "quantity": '2', "unit": 'tbsp', "preparation": 'chopped', "sort_order": 8},
        ],
    },
    {
        "name": 'Homemade Meatballs',
        "category": 'Side',
        "gluten_free": False,
        "notes": 'Source: My Diaspora Kitchen, by Chichi Uguru. When you turn off oven, leave oven door open. After a minute transfer meatballs into a clean bowl. Use immediately or freeze for later.',
        "instructions": '1. Preheat oven to 375 degrees F.\n2. Line a baking sheet with parchment paper.\n3. In a bowl, mix all ingredients with your hands until well combined.\n4. With an ice cream scoop or table spoon, scoop out ground beef mixture and arrange each scoop on your work surface.\n5. When the ground beef mix is all measured out, take each one and roll in your hands to form a smooth ball. Then transfer to the parchment paper lined baking tray. Continue till you have molded all into smooth balls.\n6. Spray meatballs with cooking spray.\n7. Put in the preheated oven and bake for 20 to 25 minutes or until the insides are no longer pink and the outside has browned beautifully.',
        "prep_time": '15 mins',
        "cook_time": '20 mins',
        "total_time": '35 mins',
        "servings": '5',
        "ingredients": [
            {"name": 'Ground beef', "quantity": '1', "unit": 'lb', "preparation": 'approx 500g', "sort_order": 0},
            {"name": 'Homemade bread crumbs', "quantity": '1/2', "unit": 'cup', "sort_order": 1},
            {"name": 'Medium onion', "quantity": '1/2', "unit": '', "preparation": 'finely chopped', "sort_order": 2},
            {"name": 'Egg', "quantity": '1', "unit": '', "sort_order": 3},
            {"name": 'Minced garlic', "quantity": '2', "unit": 'tsp', "sort_order": 4},
            {"name": 'Worcestershire sauce', "quantity": '1', "unit": 'tsp', "optional": True, "sort_order": 5},
            {"name": 'Fresh parsley', "quantity": '1', "unit": 'sprig', "preparation": 'finely chopped', "sort_order": 6},
            {"name": 'Italian seasoning', "quantity": '1', "unit": 'tsp', "sort_order": 7},
        ],
    },
    {
        "name": 'Summer Carbonara',
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: Taste of Home, by Cathy Dudderar, Lexington, Kentucky',
        "instructions": '1. Cook spaghetti according to package directions. Drain; transfer to a large bowl.\n2. Meanwhile, in a large skillet, heat oil over medium-high heat. Add onion, squash, zucchini and garlic; cook and stir until tender. Add tomatoes; heat through. Remove from pan; keep warm.\n3. Reduce heat to low. Add eggs to same skillet; cook slowly, stirring constantly, until eggs reach 160 degrees and begin to coat a metal spoon (eggs will be frothy; do not overcook). Add to hot spaghetti; toss to coat. Add vegetables and remaining ingredients; toss gently to combine.',
        "prep_time": '20 mins',
        "cook_time": '15 mins',
        "servings": '6',
        "ingredients": [
            {"name": 'Spaghetti', "quantity": '1', "unit": '16 oz package', "sort_order": 0},
            {"name": 'Olive oil', "quantity": '2', "unit": 'tbsp', "sort_order": 1},
            {"name": 'Large sweet onion', "quantity": '1', "unit": '', "preparation": 'finely chopped', "sort_order": 2},
            {"name": 'Medium yellow summer squash', "quantity": '1', "unit": '', "preparation": 'diced', "sort_order": 3},
            {"name": 'Medium zucchini', "quantity": '1', "unit": '', "preparation": 'diced', "sort_order": 4},
            {"name": 'Garlic cloves', "quantity": '2', "unit": '', "preparation": 'minced', "sort_order": 5},
            {"name": 'Plum tomatoes', "quantity": '4', "unit": '', "preparation": 'seeded and chopped', "sort_order": 6},
            {"name": 'Large eggs', "quantity": '2', "unit": '', "preparation": 'lightly beaten', "sort_order": 7},
            {"name": 'Grated Parmesan cheese', "quantity": '1', "unit": 'cup', "sort_order": 8},
            {"name": 'Bacon strips', "quantity": '12', "unit": '', "preparation": 'cooked and crumbled', "sort_order": 9},
            {"name": 'Fresh basil leaves', "quantity": '1/4', "unit": 'cup', "preparation": 'thinly sliced', "sort_order": 10},
            {"name": 'Fresh oregano', "quantity": '1', "unit": 'tsp', "preparation": 'minced', "sort_order": 11},
            {"name": 'Salt', "quantity": '1/2', "unit": 'tsp', "sort_order": 12},
            {"name": 'Pepper', "quantity": '1/4', "unit": 'tsp', "sort_order": 13},
        ],
    },
    {
        "name": 'Cheese Vegetable Chowder',
        "category": 'Soup',
        "gluten_free": False,
        "notes": 'Source: Food.com, by Bobbie. Garnish with chopped fresh parsley.',
        "instructions": '1. Bring first 6 ingredients (chicken broth, celery, carrots, potatoes, onion, pepper) to a boil in a large pot. Cover, reduce heat and simmer 20 minutes or until vegetables are tender. Remove from heat, and stir in corn.\n2. Melt butter in a heavy saucepan over low heat; add flour, whisking until smooth. Cook 1 minute, whisking constantly. Gradually whisk in milk; cook over medium heat, whisking constantly, until mixture is thickened and bubbly. Add cheese, stirring until melted.\n3. Stir cheese mixture gradually into vegetable mixture. Cook over medium heat, stirring constantly, until thoroughly heated. Serve immediately. Garnish with chopped parsley if desired.',
        "total_time": '1 hr 10 mins',
        "servings": '6-8',
        "ingredients": [
            {"name": 'Chicken broth', "quantity": '3 1/2', "unit": 'cups', "sort_order": 0},
            {"name": 'Celery ribs', "quantity": '8', "unit": '', "preparation": 'sliced', "sort_order": 1},
            {"name": 'Carrots', "quantity": '4', "unit": '', "preparation": 'sliced', "sort_order": 2},
            {"name": 'Medium potatoes', "quantity": '2', "unit": '', "preparation": 'peeled and cubed', "sort_order": 3},
            {"name": 'Large onion', "quantity": '1', "unit": '', "preparation": 'chopped', "sort_order": 4},
            {"name": 'Pepper', "quantity": '1/2', "unit": 'tsp', "sort_order": 5},
            {"name": 'Corn', "quantity": '2', "unit": 'cups', "preparation": 'canned or frozen', "sort_order": 6},
            {"name": 'Butter', "quantity": '1/4', "unit": 'cup', "sort_order": 7},
            {"name": 'Flour', "quantity": '1/4', "unit": 'cup', "sort_order": 8},
            {"name": 'Milk', "quantity": '2', "unit": 'cups', "sort_order": 9},
            {"name": 'Sharp Cheddar cheese', "quantity": '2', "unit": 'cups', "preparation": 'shredded', "sort_order": 10},
        ],
    },
    {
        "name": 'Chicken Cacciatore',
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: Just A Pinch, by Beth Pierce. Options for both stove top and baking.',
        "instructions": '1. Combine flour, salt and pepper in large sealable plastic bag. Dunk the chicken in the beaten egg. Then toss it in the flour and shake to coat.\n2. Heat 2 tablespoons vegetable oil in dutch oven or heavy ovenproof skillet over medium heat. Add chicken and brown on both sides. Once browned move to plate and set aside.\n3. Add olive oil to same pan over medium heat. Add onion and bell peppers; cook for 2-3 minutes. Add garlic, parsley and basil. Cook for additional 1 minute; stirring continuously.\n4. Return chicken to pan. Add fire roasted tomatoes, red wine and marinara. Cover pan and place in 325 degree oven for 70 minutes. If cooking on the stove top cover and simmer for 25-30 minutes.\n5. Meanwhile add butter to skillet over medium heat. Cook mushrooms until golden brown and add to the pot about 10-15 minutes before the dish is scheduled to be done.',
        "prep_time": '10 mins',
        "cook_time": '1 hr 20 mins',
        "servings": '4',
        "ingredients": [
            {"name": 'Boneless skinless chicken breasts', "quantity": '4', "unit": '', "sort_order": 0},
            {"name": 'Large egg', "quantity": '1', "unit": '', "preparation": 'beaten', "sort_order": 1},
            {"name": 'All-purpose flour', "quantity": '2/3', "unit": 'cup', "sort_order": 2},
            {"name": 'Salt', "quantity": '1/2', "unit": 'tsp', "sort_order": 3},
            {"name": 'Fresh ground black pepper', "quantity": '1/4', "unit": 'tsp', "sort_order": 4},
            {"name": 'Vegetable oil', "quantity": '2', "unit": 'tbsp', "sort_order": 5},
            {"name": 'Olive oil', "quantity": '1', "unit": 'tbsp', "sort_order": 6},
            {"name": 'Onion', "quantity": '1', "unit": '', "preparation": 'chopped', "sort_order": 7},
            {"name": 'Green bell pepper', "quantity": '1', "unit": '', "preparation": 'chopped', "sort_order": 8},
            {"name": 'Yellow or red bell pepper', "quantity": '1', "unit": '', "preparation": 'chopped', "sort_order": 9},
            {"name": 'Garlic', "quantity": '4', "unit": 'cloves', "preparation": 'minced', "sort_order": 10},
            {"name": 'Dried parsley', "quantity": '1', "unit": 'tbsp', "sort_order": 11},
            {"name": 'Dried basil', "quantity": '1', "unit": 'tsp', "sort_order": 12},
            {"name": 'Fire roasted diced tomatoes', "quantity": '1', "unit": '14.5 oz can', "sort_order": 13},
            {"name": 'Dry red wine', "quantity": '1/2', "unit": 'cup', "sort_order": 14},
            {"name": 'Marinara or tomato sauce', "quantity": '1/2', "unit": 'cup', "sort_order": 15},
            {"name": 'Butter', "quantity": '2', "unit": 'tbsp', "sort_order": 16},
            {"name": 'Cremini or white button mushrooms', "quantity": '8', "unit": 'oz', "preparation": 'quartered', "sort_order": 17},
        ],
    },
    {
        "name": 'Pastitsio',
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: Taste of Home, by Amanda Briggs, Greenfield, Wisconsin',
        "instructions": '1. Cook macaroni according to package directions. Meanwhile, in a large skillet, cook beef and onion over medium heat until meat is no longer pink. Add garlic; cook 1 minute longer. Drain. Stir in the tomato sauce, 1/2 teaspoon salt, oregano, pepper and, if desired, cinnamon; heat through.\n2. Drain macaroni; place half of macaroni in a greased 9-in. square baking pan. Sprinkle with 1/4 cup cheese. Layer with meat mixture and remaining macaroni. Set aside.\n3. Preheat oven to 350 degrees. In a small saucepan, melt butter; stir in flour and remaining salt until smooth. Gradually add milk. Bring to a boil; cook and stir 2 minutes or until thickened.\n4. Remove from the heat. Stir a small amount of the hot mixture into egg; return all to the pan, stirring constantly. Bring to a gentle boil; cook and stir 2 minutes. Remove from heat; stir in remaining cheese. Pour sauce over macaroni.\n5. Bake, uncovered, 30-35 minutes or until golden brown. Let stand 10 minutes before serving.',
        "prep_time": '35 mins',
        "cook_time": '30 mins',
        "servings": '4',
        "ingredients": [
            {"name": 'Uncooked elbow macaroni', "quantity": '1', "unit": '7 oz package', "sort_order": 0},
            {"name": 'Ground beef or lamb', "quantity": '1', "unit": 'lb', "sort_order": 1},
            {"name": 'Medium onion', "quantity": '1', "unit": '', "preparation": 'chopped', "sort_order": 2},
            {"name": 'Garlic clove', "quantity": '1', "unit": '', "preparation": 'minced', "sort_order": 3},
            {"name": 'Tomato sauce', "quantity": '1', "unit": '8 oz can', "sort_order": 4},
            {"name": 'Salt', "quantity": '1', "unit": 'tsp', "preparation": 'divided', "sort_order": 5},
            {"name": 'Dried oregano', "quantity": '1/4', "unit": 'tsp', "sort_order": 6},
            {"name": 'Pepper', "quantity": '1/8', "unit": 'tsp', "sort_order": 7},
            {"name": 'Ground cinnamon', "quantity": '1/4', "unit": 'tsp', "optional": True, "sort_order": 8},
            {"name": 'Grated Parmesan cheese', "quantity": '1/2', "unit": 'cup', "preparation": 'divided', "sort_order": 9},
            {"name": 'Butter', "quantity": '3', "unit": 'tbsp', "sort_order": 10},
            {"name": 'All-purpose flour', "quantity": '3', "unit": 'tbsp', "sort_order": 11},
            {"name": '2% milk', "quantity": '1 1/2', "unit": 'cups', "sort_order": 12},
            {"name": 'Large egg', "quantity": '1', "unit": '', "preparation": 'lightly beaten', "sort_order": 13},
        ],
    },
    {
        "name": 'Classic Spaghetti and Parmesan Meatballs',
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: Allrecipes / Hunts.com',
        "instructions": '1. Preheat oven to 375 degrees F.\n2. Combine beef, 1/2 cup Parmesan cheese, parsley, egg, 1 teaspoon garlic and salt in medium bowl. Divide mixture into 12 portions; shape into meatballs and place on aluminum foil-lined shallow baking pan.\n3. Bake 15 minutes or until done (160 degrees F).\n4. Heat oil in large skillet over medium-high heat. Add onion; cook 4 minutes or until tender, stirring occasionally. Add remaining 2 teaspoons garlic, cook 1 minute more or until fragrant. Stir in undrained tomatoes, tomato sauce, remaining 1/4 cup Parmesan cheese, basil and sugar. Bring to a boil. Add meatballs to sauce; gently stir to coat. Reduce heat and simmer 10 minutes or until sauce has thickened slightly, stirring occasionally.\n5. Meanwhile, cook spaghetti according to package directions. Drain spaghetti; top with sauce and meatballs.',
        "prep_time": '40 mins',
        "cook_time": '15 mins',
        "total_time": '55 mins',
        "servings": '6',
        "ingredients": [
            {"name": 'Ground round beef (85% lean)', "quantity": '1', "unit": 'lb', "sort_order": 0},
            {"name": 'Grated Parmesan cheese', "quantity": '3/4', "unit": 'cup', "preparation": 'divided', "sort_order": 1},
            {"name": 'Fresh Italian parsley', "quantity": '1/4', "unit": 'cup', "preparation": 'chopped', "sort_order": 2},
            {"name": 'Egg', "quantity": '1', "unit": '', "preparation": 'slightly beaten', "sort_order": 3},
            {"name": 'Garlic', "quantity": '1', "unit": 'tbsp', "preparation": 'finely chopped, divided', "sort_order": 4},
            {"name": 'Salt', "quantity": '1/4', "unit": 'tsp', "sort_order": 5},
            {"name": 'Olive oil', "quantity": '1', "unit": 'tbsp', "sort_order": 6},
            {"name": 'Yellow onion', "quantity": '3/4', "unit": 'cup', "preparation": 'finely chopped', "sort_order": 7},
            {"name": 'Diced tomatoes', "quantity": '1', "unit": '14.5 oz can', "preparation": 'undrained', "sort_order": 8},
            {"name": 'Tomato sauce', "quantity": '2', "unit": 'cups', "sort_order": 9},
            {"name": 'Fresh basil', "quantity": '1/4', "unit": 'cup', "preparation": 'chopped', "sort_order": 10},
            {"name": 'Granulated sugar', "quantity": '1', "unit": 'tbsp', "sort_order": 11},
            {"name": 'Dry spaghetti', "quantity": '12', "unit": 'oz', "preparation": 'uncooked', "sort_order": 12},
        ],
    },
    {
        "name": 'Easy PB+J Sandwich Donuts',
        "category": 'Dessert',
        "gluten_free": False,
        "notes": 'Source: Joy the Baker',
        "instructions": "1. To make the batter: in a small bowl whisk together eggs, flour, milk, and water. The batter will have a drippy thickness, but try to whisk out most of the lumps. Set aside.\n2. Next, slice the brioche and cut off the crusts if you'd like. Dollop about 2 tablespoons of peanut butter into the center of two slices of bread. Top with about 2 tablespoons of strawberry jam. Top with the remaining pieces of brioche, and lightly press around the edges so the peanut butter and jam don't seep out.\n3. In a medium and shallow bowl or plate, stir together sugar and cinnamon.\n4. In a medium saucepan, heat about 2 inches of canola oil. Use a fry thermometer to bring the oil up to 340 degrees F.\n5. Have a plate covered with paper towels and a wire rack ready.\n6. Working quickly, take a brioche sandwich and quickly dip it in the batter, making sure to further press and seal the edges as they become moistened. Carefully lower the sandwich into the oil and cook for about 45 seconds on each side, or until golden. Remove the sandwich with a slotted spoon and place on the paper towels to drain for a few seconds. While still warm, flip into the cinnamon sugar mixture until coated on all sides. Serve immediately.",
        "servings": '2',
        "ingredients": [
            {"name": 'Brioche bread', "quantity": '4', "unit": 'slices', "preparation": '1/2 to 3/4 inch thick', "sort_order": 0},
            {"name": 'Smooth peanut butter', "quantity": '1/4', "unit": 'cup', "sort_order": 1},
            {"name": 'Strawberry jam', "quantity": '1/4', "unit": 'cup', "sort_order": 2},
            {"name": 'Canola oil', "quantity": '', "unit": '', "preparation": 'for frying', "sort_order": 3},
            {"name": 'Large eggs', "quantity": '2', "unit": '', "preparation": 'for batter', "sort_order": 4},
            {"name": 'All-purpose flour', "quantity": '1/3', "unit": 'cup', "preparation": 'for batter', "sort_order": 5},
            {"name": 'Whole milk', "quantity": '1/3', "unit": 'cup', "preparation": 'for batter', "sort_order": 6},
            {"name": 'Water', "quantity": '2', "unit": 'tbsp', "preparation": 'for batter', "sort_order": 7},
            {"name": 'Granulated sugar', "quantity": '3/4', "unit": 'cup', "preparation": 'for coating', "sort_order": 8},
            {"name": 'Ground cinnamon', "quantity": '1/2', "unit": 'tsp', "preparation": 'for coating', "sort_order": 9},
        ],
    },
    {
        "name": 'Butternut Squash Soup with Coconut Milk and Ginger',
        "category": 'Soup',
        "gluten_free": True,
        "notes": 'Source: Martha Stewart. Vegan. Soup can be stored in an airtight container in refrigerator up to 1 week.',
        "instructions": '1. Preheat oven to 400 degrees. Cut squash in half lengthwise and scoop out seeds; reserve, if desired. Drizzle cut side of squash with 1 tablespoon oil and season with salt and pepper. Place, cut-side down, on a foil-lined rimmed baking sheet. Roast until squash is very tender when pierced with the tip of a knife, 50 to 55 minutes. Let cool slightly, about 15 minutes.\n2. In a 6-quart pot or Dutch oven, heat remaining 2 tablespoons oil over medium. Add shallots and garlic, season with salt and pepper, and cook until shallots are soft and translucent, 6 to 8 minutes. Add ginger and coriander; cook until very fragrant, 2 minutes. Stir in broth, 1 cup water, and 1 teaspoon salt. Scoop flesh from cooled squash into pot. Bring to a boil, then reduce heat to medium-low and simmer, stirring a few times, 30 minutes. Let cool 5 minutes.\n3. Working in batches, puree soup in a blender until smooth. Return to pot; heat over medium. Whisk in coconut milk. Cook until warmed through, 5 minutes. Remove from heat and stir in lime juice. Season to taste with salt and pepper. Serve, drizzled with more coconut milk and sprinkled with toasted squash seeds, if desired.',
        "prep_time": '40 mins',
        "total_time": '2 hrs 20 mins',
        "servings": '6-8',
        "ingredients": [
            {"name": 'Medium butternut squash', "quantity": '1', "unit": '', "preparation": '3 pounds', "sort_order": 0},
            {"name": 'Safflower or neutral-flavored oil', "quantity": '3', "unit": 'tbsp', "sort_order": 1},
            {"name": 'Kosher salt and freshly ground pepper', "quantity": '', "unit": '', "sort_order": 2},
            {"name": 'Shallots', "quantity": '3/4', "unit": 'cup', "preparation": 'thinly sliced (3 medium)', "sort_order": 3},
            {"name": 'Garlic', "quantity": '3', "unit": 'cloves', "preparation": 'smashed and peeled', "sort_order": 4},
            {"name": 'Fresh ginger', "quantity": '2', "unit": 'tbsp', "preparation": 'minced (from a 2-inch piece)', "sort_order": 5},
            {"name": 'Ground coriander', "quantity": '3/4', "unit": 'tsp', "sort_order": 6},
            {"name": 'Low-sodium vegetable broth', "quantity": '4', "unit": 'cups', "sort_order": 7},
            {"name": 'Coconut milk', "quantity": '1/2', "unit": 'cup', "preparation": 'plus more for serving', "sort_order": 8},
            {"name": 'Fresh lime juice', "quantity": '1', "unit": 'tbsp', "preparation": 'from 1/2 lime', "sort_order": 9},
        ],
    },
    {
        "name": 'Butternut Squash Soup with Chicken Sausage',
        "category": 'Soup',
        "gluten_free": True,
        "notes": 'Source: Food Network Kitchen',
        "instructions": '1. Heat 1 tablespoon olive oil in a large pot over medium-high heat. Add the sausage and cook, stirring occasionally, until browned, about 4 minutes. Transfer to a bowl using a slotted spoon. Add the squash, carrots, celery, onion, chicken broth, 2 1/2 cups water and 3/4 teaspoon salt to the pot. Cover and bring to a simmer, then reduce the heat to low and continue simmering until the vegetables are tender, about 15 more minutes.\n2. Puree the soup in a blender in batches, then return to the pot along with the sausage. Season with salt and pepper and keep warm.\n3. Heat the remaining 1/3 cup olive oil in a small saucepan over medium-high heat. When the oil is very hot, add the sage leaves in batches and fry, turning, until dark green and crisp, about 1 minute. Remove with a slotted spoon and drain on paper towels. Ladle the soup into bowls and top with the fried sage.',
        "prep_time": '20 mins',
        "cook_time": '20 mins',
        "total_time": '40 mins',
        "servings": '4',
        "ingredients": [
            {"name": 'Extra-virgin olive oil', "quantity": '1/3 cup + 1 tbsp', "unit": '', "sort_order": 0},
            {"name": 'Cooked chicken-apple sausage', "quantity": '12', "unit": 'oz', "preparation": 'cut into 1/2-inch pieces', "sort_order": 1},
            {"name": 'Butternut squash', "quantity": '4', "unit": 'cups', "preparation": 'cubed, peeled (1 small to medium squash)', "sort_order": 2},
            {"name": 'Medium carrots', "quantity": '3', "unit": '', "preparation": 'chopped', "sort_order": 3},
            {"name": 'Celery', "quantity": '1', "unit": 'stalk', "preparation": 'chopped', "sort_order": 4},
            {"name": 'Medium onion', "quantity": '1/2', "unit": '', "preparation": 'chopped', "sort_order": 5},
            {"name": 'Low-sodium chicken broth', "quantity": '2 1/2', "unit": 'cups', "sort_order": 6},
            {"name": 'Kosher salt and freshly ground pepper', "quantity": '', "unit": '', "sort_order": 7},
            {"name": 'Fresh sage or parsley leaves', "quantity": '1/2', "unit": 'cup', "sort_order": 8},
        ],
    },
    {
        "name": 'Butternut Squash Mash',
        "category": 'Side',
        "gluten_free": True,
        "notes": 'Source: Martha Stewart. Rich in vitamin A and potassium.',
        "instructions": '1. Heat oil in a large pot over medium-high heat. Add squashes and salt. Cover, and cook, stirring occasionally, until partially tender, about 8 minutes (reduce heat if squash begins to brown). Add 1 cup water, cover, and simmer over medium-high heat until completely tender and water has mostly evaporated, about 15 minutes. Mash with a potato masher. Season with pepper.',
        "servings": '7',
        "ingredients": [
            {"name": 'Extra-virgin olive oil', "quantity": '2', "unit": 'tbsp', "sort_order": 0},
            {"name": 'Large butternut squashes', "quantity": '2', "unit": '', "preparation": 'trimmed, peeled, seeded, and cut into 3/4-inch chunks', "sort_order": 1},
            {"name": 'Coarse salt', "quantity": '1', "unit": 'tsp', "sort_order": 2},
            {"name": 'Pepper', "quantity": '', "unit": '', "preparation": 'to taste', "sort_order": 3},
        ],
    },
    {
        "name": 'Creamed Pearl Onions',
        "category": 'Side',
        "gluten_free": False,
        "notes": 'Source: Taste of Home, by Barbara Caserman, Lake Havasu City, Arizona. Can be prepared a day in advance.',
        "instructions": '1. In a Dutch oven or large kettle, bring 8 cups water to a boil. Add pearl onions; boil until tender, 6-7 minutes. Drain and rinse in cold water; peel and set aside.\n2. In a saucepan, melt butter. Stir in the flour, salt and pepper until smooth. Gradually stir in broth and cream. Bring to a boil; cook and stir for 2 minutes or until thickened. Stir in the parsley, cheese and onions.\n3. Pour into an ungreased 1-1/2-qt. baking dish. Cover and refrigerate overnight. Remove from the refrigerator 30 minutes before baking. Cover and bake at 350 degrees for 15 minutes; stir. Top with pimientos if desired. Bake, uncovered, 10 minutes longer or until bubbly and heated through.',
        "prep_time": '30 mins',
        "cook_time": '25 mins',
        "servings": '6',
        "ingredients": [
            {"name": 'Pearl onions', "quantity": '4', "unit": 'cups', "sort_order": 0},
            {"name": 'Butter', "quantity": '3', "unit": 'tbsp', "sort_order": 1},
            {"name": 'All-purpose flour', "quantity": '3', "unit": 'tbsp', "sort_order": 2},
            {"name": 'Salt', "quantity": '1/2', "unit": 'tsp', "sort_order": 3},
            {"name": 'Pepper', "quantity": '', "unit": 'dash', "sort_order": 4},
            {"name": 'Chicken broth', "quantity": '3/4', "unit": 'cup', "sort_order": 5},
            {"name": 'Half-and-half cream', "quantity": '3/4', "unit": 'cup', "sort_order": 6},
            {"name": 'Fresh parsley', "quantity": '1/4', "unit": 'cup', "preparation": 'minced', "sort_order": 7},
            {"name": 'Grated Parmesan cheese', "quantity": '3', "unit": 'tbsp', "sort_order": 8},
            {"name": 'Pimiento strips', "quantity": '', "unit": '', "optional": True, "sort_order": 9},
        ],
    },
    {
        "name": 'Tuna Casserole',
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: Martha Stewart',
        "instructions": '1. Preheat oven to 425 degrees. In a large pot of boiling salted water, cook pasta 2 minutes less than package instructions (it will be undercooked). Drain. In a small bowl, toss together panko, Parmesan, and 2 teaspoons oil.\n2. In pot, heat 2 tablespoons oil over medium-high. Add onion, season with salt and pepper, and cook until softened, 8 minutes. Add flour and whisk to coat onion with flour. Slowly whisk in broth, then milk.\n3. Cook, stirring constantly, until sauce comes to a boil. Reduce heat and simmer, stirring frequently, until sauce is thickened, about 8 minutes. Stir in pasta, tuna, and peas and season to taste with salt and pepper.\n4. Transfer tuna mixture to a 9-by-13-inch baking dish and top with panko mixture. Bake until sauce is bubbling and crust is golden, 17 to 20 minutes. Let cool 10 minutes before serving.',
        "prep_time": '35 mins',
        "total_time": '1 hr',
        "servings": '8',
        "ingredients": [
            {"name": 'Coarse salt and ground pepper', "quantity": '', "unit": '', "sort_order": 0},
            {"name": 'Tubetti or elbow macaroni', "quantity": '3/4', "unit": 'lb', "sort_order": 1},
            {"name": 'Panko (Japanese breadcrumbs)', "quantity": '1', "unit": 'cup', "sort_order": 2},
            {"name": 'Parmesan', "quantity": '1/2', "unit": 'oz', "preparation": 'grated (2 tablespoons)', "sort_order": 3},
            {"name": 'Extra-virgin olive oil', "quantity": '2 tbsp + 2 tsp', "unit": '', "sort_order": 4},
            {"name": 'Yellow onion', "quantity": '1', "unit": '', "preparation": 'diced small', "sort_order": 5},
            {"name": 'All-purpose flour', "quantity": '3', "unit": 'tbsp', "sort_order": 6},
            {"name": 'Low-sodium chicken broth', "quantity": '2 1/2', "unit": 'cups', "sort_order": 7},
            {"name": 'Whole milk', "quantity": '1 1/2', "unit": 'cups', "sort_order": 8},
            {"name": 'Solid light tuna packed in water', "quantity": '2', "unit": '6 oz cans', "preparation": 'drained and flaked', "sort_order": 9},
            {"name": 'Frozen peas', "quantity": '1', "unit": 'cup', "preparation": 'thawed', "sort_order": 10},
        ],
    },
    {
        "name": "Campbell's Tuna Noodle Casserole",
        "category": 'Main',
        "gluten_free": False,
        "notes": 'Source: Allrecipes. For a Cheese Topping: In place of buttered breadcrumbs, top with 1/2 cup shredded Cheddar cheese. For Chicken Noodle Casserole: Substitute about 2 cups cooked cubed chicken for tuna.',
        "instructions": '1. Stir soup, milk, peas, tuna and noodles in 3-quart casserole.\n2. Bake at 400 degrees F for 30 minutes or until hot. Stir.\n3. Mix bread crumbs with butter in bowl and sprinkle over tuna mixture. Bake for 5 minutes more.',
        "prep_time": '10 mins',
        "cook_time": '35 mins',
        "total_time": '45 mins',
        "servings": '8',
        "ingredients": [
            {"name": 'Condensed Cream of Mushroom Soup', "quantity": '2', "unit": '10.75 oz cans', "preparation": 'regular or 25% Lower Sodium', "sort_order": 0},
            {"name": 'Milk', "quantity": '1', "unit": 'cup', "sort_order": 1},
            {"name": 'Frozen peas', "quantity": '2', "unit": 'cups', "sort_order": 2},
            {"name": 'Tuna', "quantity": '2', "unit": '10 oz cans', "preparation": 'drained', "sort_order": 3},
            {"name": 'Hot cooked medium egg noodles', "quantity": '4', "unit": 'cups', "sort_order": 4},
            {"name": 'Dry bread crumbs', "quantity": '2', "unit": 'tbsp', "sort_order": 5},
            {"name": 'Butter', "quantity": '1', "unit": 'tbsp', "preparation": 'melted', "sort_order": 6},
        ],
    },
    {
        "name": 'Fresh Strawberry Cobbler',
        "category": 'Dessert',
        "gluten_free": False,
        "notes": 'Source: Food.com, by ratherbeswimmin',
        "instructions": '1. Beat 1/4 cup softened butter at medium speed with an electric mixer; gradually add 3/4 cup sugar, beating well.\n2. Add egg and vanilla, beating well.\n3. Combine 1 1/4 cup flour, baking powder, and salt; add to butter mixture alternately with milk, beginning and ending with flour mixture.\n4. Spoon mixture into a greased 8-inch square baking dish.\n5. Arrange strawberries on top, cut side down.\n6. Combine 1/4 cup flour and 1/4 cup sugar; cut in 1/4 cup chilled butter with pastry blender until crumbly.\n7. Sprinkle over strawberries.\n8. Bake at 350 degrees for 1 hour or until a wooden pick inserted in center comes out clean.',
        "total_time": '1 hr 20 mins',
        "servings": '8',
        "ingredients": [
            {"name": 'Butter or margarine', "quantity": '1/4', "unit": 'cup', "preparation": 'softened', "sort_order": 0},
            {"name": 'Sugar', "quantity": '3/4', "unit": 'cup', "sort_order": 1},
            {"name": 'Large egg', "quantity": '1', "unit": '', "sort_order": 2},
            {"name": 'Vanilla extract', "quantity": '1', "unit": 'tsp', "sort_order": 3},
            {"name": 'All-purpose flour', "quantity": '1 1/4', "unit": 'cups', "sort_order": 4},
            {"name": 'Baking powder', "quantity": '1 1/2', "unit": 'tsp', "sort_order": 5},
            {"name": 'Salt', "quantity": '1/2', "unit": 'tsp', "sort_order": 6},
            {"name": 'Milk', "quantity": '1/2', "unit": 'cup', "sort_order": 7},
            {"name": 'Fresh strawberries', "quantity": '3', "unit": 'cups', "preparation": 'cut in half lengthwise', "sort_order": 8},
            {"name": 'All-purpose flour', "quantity": '1/4', "unit": 'cup', "preparation": 'for topping', "sort_order": 9},
            {"name": 'Sugar', "quantity": '1/4', "unit": 'cup', "preparation": 'for topping', "sort_order": 10},
            {"name": 'Butter or margarine', "quantity": '1/4', "unit": 'cup', "preparation": 'chilled, for topping', "sort_order": 11},
        ],
    },
    {
        "name": 'Strawberry Cobbler (Paula Todora)',
        "category": 'Dessert',
        "gluten_free": False,
        "notes": 'Source: Just A Pinch, by Paula Todora. Moist and great warm with vanilla ice cream.',
        "instructions": "1. Preheat oven to 375 degrees. Spray a 9-inch pie pan or baking dish with nonstick cooking spray.\n2. In a medium bowl add strawberries and 3/4 cup sugar; mix with a spoon and let sit.\n3. In a large bowl whisk flour, baking powder, salt and 1/2 cup sugar to blend well. Add milk and melted butter; mix with a spoon.\n4. Pour batter into prepared pan and pour strawberries on top. Don't mix. Bake 40 minutes. Serve warm.",
        "prep_time": '15 mins',
        "cook_time": '40 mins',
        "servings": '6',
        "ingredients": [
            {"name": 'Fresh strawberries', "quantity": '3', "unit": 'cups', "preparation": 'stems removed, sliced or diced', "sort_order": 0},
            {"name": 'Sugar', "quantity": '3/4', "unit": 'cup', "preparation": 'for strawberries', "sort_order": 1},
            {"name": 'Flour', "quantity": '1', "unit": 'cup', "sort_order": 2},
            {"name": 'Baking powder', "quantity": '2', "unit": 'tsp', "sort_order": 3},
            {"name": 'Salt', "quantity": '1/2', "unit": 'tsp', "sort_order": 4},
            {"name": 'Sugar', "quantity": '1/2', "unit": 'cup', "preparation": 'for batter', "sort_order": 5},
            {"name": 'Milk', "quantity": '1', "unit": 'cup', "sort_order": 6},
            {"name": 'Butter', "quantity": '1', "unit": 'stick', "preparation": 'melted', "sort_order": 7},
        ],
    },
    {
        "name": 'Strawberry Cobbler (I Heart Recipes)',
        "category": 'Dessert',
        "gluten_free": False,
        "notes": 'Source: I Heart Recipes. Can be made with fresh or frozen strawberries. Serve with ice cream.',
        "instructions": '1. Preheat oven to 350 degrees. Grease a 8x8 baking pan and set aside.\n2. Add the softened butter and sugar in a large mixing bowl. Cream together with an electric mixer on medium speed.\n3. Add the egg and vanilla extract and mix for an additional 30 seconds. Set aside.\n4. In a medium mixing bowl, whisk together the flour, baking powder and salt. Mix in half of the dry ingredients to the creamed butter.\n5. Add in 1/4 cup of the milk and stir until mixed. Add the remaining flour and the remaining milk. Stir again until all of the ingredients are wet.\n6. Transfer the batter to your greased pan, and even the batter out.\n7. In a small bowl, whisk together 1/4 cup flour and 1/4 cup sugar. With a pastry blender or using 2 forks, cut in the chilled butter slices until crumbly.\n8. Place a layer of strawberries on top of the batter, cut side facing down.\n9. Sprinkle the crumbly mixture on top of the strawberries.\n10. Bake at 350 degrees for 45 minutes, or until an inserted toothpick comes out clean.\n11. Let the strawberry cobbler cool down.\n12. Serve, and enjoy with ice cream!',
        "prep_time": '10 mins',
        "cook_time": '45 mins',
        "total_time": '55 mins',
        "servings": '8',
        "ingredients": [
            {"name": 'Unsalted butter', "quantity": '1/4', "unit": 'cup', "preparation": 'softened, for batter', "sort_order": 0},
            {"name": 'Granulated sugar', "quantity": '3/4', "unit": 'cup', "preparation": 'for batter', "sort_order": 1},
            {"name": 'Large egg', "quantity": '1', "unit": '', "sort_order": 2},
            {"name": 'Vanilla extract', "quantity": '2', "unit": 'tsp', "sort_order": 3},
            {"name": 'All-purpose flour', "quantity": '1 1/4', "unit": 'cups', "preparation": 'divided', "sort_order": 4},
            {"name": 'Baking powder', "quantity": '1 1/2', "unit": 'tsp', "sort_order": 5},
            {"name": 'Salt', "quantity": '1/2', "unit": 'tsp', "sort_order": 6},
            {"name": 'Milk', "quantity": '1/2', "unit": 'cup', "sort_order": 7},
            {"name": 'Fresh or frozen strawberries', "quantity": '2', "unit": 'cups', "preparation": 'sliced', "sort_order": 8},
            {"name": 'All-purpose flour', "quantity": '1/4', "unit": 'cup', "preparation": 'for topping', "sort_order": 9},
            {"name": 'Granulated sugar', "quantity": '1/4', "unit": 'cup', "preparation": 'for topping', "sort_order": 10},
            {"name": 'Cold unsalted butter', "quantity": '1/4', "unit": 'cup', "preparation": 'cut into small pieces, for topping', "sort_order": 11},
        ],
    },
    {
        "name": 'Simple Strawberry Cobbler',
        "category": 'Dessert',
        "gluten_free": False,
        "notes": 'Source: Food.com, by FlemishMinx. Serve with whipped cream or vanilla ice cream.',
        "instructions": '1. Pre-heat oven to 375 degrees F.\n2. Spread the sliced strawberries evenly in an 8 or 9 inch square baking dish.\n3. In a medium sized bowl, mix together the flour, baking powder and sugar.\n4. Add the egg, and mix (a fork works best) till crumbly and the dry ingredients are completely incorporated.\n5. Spread this over the berries.\n6. Dot with the butter cubes.\n7. Bake for 45-50 minutes, until the top is golden and the berries are bubbling.\n8. Cool slightly before serving.',
        "total_time": '1 hr',
        "servings": '4-6',
        "ingredients": [
            {"name": 'Strawberries', "quantity": '4', "unit": 'cups', "preparation": 'cleaned and sliced', "sort_order": 0},
            {"name": 'All-purpose flour', "quantity": '1', "unit": 'cup', "sort_order": 1},
            {"name": 'Baking powder', "quantity": '1/2', "unit": 'tsp', "sort_order": 2},
            {"name": 'Sugar', "quantity": '1', "unit": 'cup', "sort_order": 3},
            {"name": 'Egg', "quantity": '1', "unit": '', "preparation": 'beaten', "sort_order": 4},
            {"name": 'Butter', "quantity": '1/4', "unit": 'cup', "preparation": 'in cubes', "sort_order": 5},
        ],
    },
]
